import { buildLexicon, type VehicleLexicon } from './fuzzy-vehicle-name';

/** Solo tests: filas tipo patio, no es la lista de producción. */
export const TEST_LEXICON: VehicleLexicon = buildLexicon([
  { brand: 'chevrolet', model: 'grand vitara 3p tm ac sport' },
  { brand: 'chevrolet', model: 'd-max crdi 2.5 cd 4x4 tm diesel' },
  { brand: 'chevrolet', model: 'aveo ls ac 1.6' },
  { brand: 'chevrolet', model: 'optra advance 1.8l' },
  { brand: 'suzuki', model: 'grand vitara sz ac 2.0' },
  { brand: 'jetour', model: 'x70 ii ac 1.5' },
  { brand: 'jetour', model: 't1 ac 2.0 5p 4x4 ta' },
  { brand: 'kia', model: 'sportage r gti' },
  { brand: 'kia', model: 'seltos ex' },
  { brand: 'kia', model: 'rio lx' },
  { brand: 'kia', model: 'picanto lx' },
  { brand: 'toyota', model: 'hilux 2.4 cd' },
  { brand: 'toyota', model: '4 runner 4x2 t/a' },
  { brand: 'toyota', model: 'prado txl' },
  { brand: 'nissan', model: 'x-trail sense' },
  { brand: 'nissan', model: 'sentra exclusive' },
  { brand: 'hyundai', model: 'tucson gl' },
  { brand: 'hyundai', model: 'kona gl' },
  { brand: 'hyundai', model: 'creta ac 1.5 5p 4x2 tm' },
  { brand: 'hyundai', model: 'santa fe dm 7pas ac 2.4 5p 4x2' },
  { brand: 'ford', model: 'explorer xlt' },
  { brand: 'ford', model: 'f-150' },
  { brand: 'volkswagen', model: 't-cross' },
  { brand: 'great wall', model: 'poer 2.0' },
  { brand: 'great wall', model: 'hunter ac 2.4 cd' },
  { brand: 'mitsubishi', model: 'l200 2.4 cd' },
  { brand: 'peugeot', model: '2008 fin' },
  { brand: 'peugeot', model: '3008n' },
  { brand: 'ram', model: 'ram 700 slt ac 1.4 cs 4x2 tm' },
  { brand: 'ram', model: 'ram 1500 laramie 4x4' },
  { brand: 'fiat', model: '500 lounge ac 1.4 3p 4x2 tm' },
  { brand: 'mitsubishi', model: 'montero sport gls ac 3.0 5p 4x4' },
]);
